// console.log("divyashu");
// try {
//     console.log("Try block start here");
//     // let x = 3;
//     console.log(x);
//     console.log("try block end here");
    
// } catch (error) {
//     console.log("catch block is running");
//     console.log("your error is here")
// }
// finally{
//     console.log("error ko hone do mai toh print hunga naa!!");
    
// }

//  throw error and custom here we created 

try {
    // Refrence error
    console.log(y);
    
} catch (error) {
    // using throw
    throw new Error("bhai y ki value define kr de") 
}